### ISSUE TITLE
something new 

### ISSUE THREAD

**Issue by atrueikun** [run-bigpig/mxbc#2]
i found it have added a new type_1286,

**Comment by Nswhisper** [comment]
确实是，没有type_1286就会错误，这是今天才加的吗

**Comment by long1183551588** [comment]
好像不是错误，返回了一个html，里面带js，会修改url

**Comment by Nswhisper** [comment]
> 好像不是错误，返回了一个html，里面带js，会修改url
就是错误，返回js就是请求包有问题。正常的响应包是个json

**Comment by long1183551588** [comment]
他返回的html里面的js就是type1286=后面的算法

**Comment by atrueikun** [comment]
怎么改啊

**Comment by faintout** [comment]
求算法，没找到这个参数的加密算法呢
